{% set version = "0.9.25" %}

package:
  name: aioquic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aioquic/aioquic-{{ version }}.tar.gz
  sha256: 70795c78905326d855c2ae524072234aae586c789b81292e272d021e9b0430a3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
  run:
    - certifi
    - cryptography
    - openssl
    - pylsqpack >=0.3.3,<0.4.0
    - pyopenssl >=22
    - python
    - service-identity >=23.1.0

test:
  source_files:
    - tests
  imports:
    - aioquic
    - aioquic._buffer
    - aioquic._crypto
  requires:
    - coverage
    - pip
    - pytest
  commands:
    - pip check
    - coverage run --source=aioquic --branch -m pytest -vv --tb=long --color=yes -k "not connect_and_serve_ipv6"
    - coverage report --show-missing --skip-covered --fail-under=99  # [linux]

about:
  home: https://github.com/aiortc/aioquic
  summary: An implementation of QUIC and HTTP/3
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://aioquic.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
