{% set version = "1.2.0" %}

package:
  name: aioquic
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/aioquic/aioquic-{{ version }}.tar.gz
  sha256: f91263bb3f71948c5c8915b4d50ee370004f20a416f67fab3dcc90556c7e7199

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - certifi
    - cryptography >=42.0.0
    - openssl
    - pylsqpack >=0.3.3,<0.4.0
    - pyopenssl
    - python
    - service-identity >=24.1.0

test:
  source_files:
    - tests
  imports:
    - aioquic
    - aioquic._buffer
    - aioquic._crypto
  requires:
    - coverage
    - pip
    - pytest
  commands:
    - pip check
    - coverage run --source=aioquic --branch -m pytest -vv --tb=long --color=yes -k "not connect_and_serve_ipv6"
    - coverage report --show-missing --skip-covered --fail-under=99  # [linux]

about:
  home: https://github.com/aiortc/aioquic
  summary: An implementation of QUIC and HTTP/3
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://aioquic.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
